### ISSUE TITLE
Module: Not all audioaddict.com radios are supported

### ISSUE THREAD

**Issue by svekl** [PoziWorld/PoziTone#14]
Looks like not all radios from audioaddict.com work, have success only with
http://www.di.fm/

But those ones doesn't work for some reason:
http://www.jazzradio.com/
http://www.radiotunes.com/
http://www.rockradio.com/
http://www.classicalradio.com/

**Comment by PoziWorld** [comment]
Thank you for your feedback, but they aren't actually meant to work. 
At the moment, PoziTone supports only di.fm, as you noted.

I realize that “Built-in modules” page might have made you think they are supposed to be supported, but they aren't.

audioaddict.com there just means that di.fm loads some data from that domain (for example, station logos), that's why PoziTone needs access to that domain.

Sorry for the confusion.


Do you use those radios?

**Comment by svekl** [comment]
Not all, only
http://www.radiotunes.com/
and
http://www.jazzradio.com/

And I believe they all share same engine, so same code could work for all.
But, for my shame, I can't understand how your module system works and how di.fm module is searching for it's tab.

**Comment by PoziWorld** [comment]
Unfortunately, di.fm module has been created before I had the API in place. It'll take a little effort to make it API-compliant.

I'll check radiotunes.com and jazzradio.com later to see how easy it will be to adapt DI's module to work with them.

Thank you for letting me know.

**Comment by PoziWorld** [comment]
@svekl, seems like both, radiotunes.com and jazzradio.com, use a template that di.fm used to have before they redesigned their website ~1.5 years ago.

Most of the code for the old version of the di.fm module should work fine on those sites. 
I'll try to find some time to add support for both of them as it shouldn't take long.

Here is the old di.fm module code – https://github.com/PoziWorld/PoziTone/commit/4e2f8d87f0c39b0c91151ca3381b303f0e9a09d9#diff-b0c5146c4f2efda511175238eb609f23

**Comment by svekl** [comment]
Wow, great news. Right, now I remember, what you're talking about, when di.fm changed some time ago. Looks like di.fm is their flagship, and other sites are adopted later.

**Comment by PoziWorld** [comment]
@svekl, it works! Just needs a few tweaks. I'll let you know when it's ready.

Thank you for letting me know about those sites!

**Comment by PoziWorld** [comment]
@svekl, to credit you for the idea, when I announce the new version, which one of the following should I use?

* Idea by Sergey Svekolnikov
* Idea by Sergey Svekolnikov aka svekl
* Idea by svekl
* Idea by Sergey "svekl" Svekolnikov

I hope I didn't misspell your name.

**Comment by svekl** [comment]
It doesn't really matter, for example first is good ) Thank you for your time and great extension.

**Comment by PoziWorld** [comment]
Thank you for providing valuable input and praises!

**Comment by PoziWorld** [comment]
@svekl, the requested functionality has been added in v0.6.5.
You should receive an automatic update soon.

Thank you again!

**Comment by svekl** [comment]
Wow, works great, thank you so much!
